/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agregar;

import Classes.Candidato;
import DBHelper.CandidatoDBHelper;
import Interfaz.NewJFrameCandidato;
import javax.swing.JOptionPane;

/**
 *
 * @author DEll
 */
public class JFrame_AgregarCandidato extends javax.swing.JFrame {
  
    private  Candidato can;
    private CandidatoDBHelper canDB;
    private NewJFrameCandidato newJfCandi;
    private String trabajo;
    private int nuevoID;
    private String lugarDeTrabajo;
    private String hora;
    public JFrame_AgregarCandidato() {
        initComponents();
        lugarDeTrabajo=null;
        hora=null;
        //--------------------------------------------------
        this.setLocationRelativeTo(null);
        jPanel_Lugar.setVisible(false);
        jTextField_ID.setVisible(false);
        newJfCandi=new NewJFrameCandidato();
        this.setTitle("Agregar Candidato");
        //--------------------------------------------------
        can = new Candidato();
        canDB= new CandidatoDBHelper();
        nuevoID=canDB.TamaCandidatoRegistro();
        jTextField_ID.setText(""+nuevoID);
    }

    
    public JFrame_AgregarCandidato(Candidato can) {
        this();
        this.can= can;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jButton_Aceptar = new javax.swing.JButton();
        jButton_Cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_TemaTesis = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel_Lugar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_LugarDeTrabajo = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jTextField_Hora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_Hora2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel_Trabajo = new javax.swing.JPanel();
        jRadioButton_Si = new javax.swing.JRadioButton();
        jRadioButton_No = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jTextField_AppPaterno = new javax.swing.JTextField();
        jTextField_AppMaterno = new javax.swing.JTextField();
        jTextField_Correo = new javax.swing.JTextField();
        jTextField_Telefono = new javax.swing.JTextField();
        jTextField_Carrera = new javax.swing.JTextField();
        jTextField_Generacion = new javax.swing.JTextField();
        jTextField_DirectorDeTesis = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_Id_DirectorDeTesis = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextField_Foto = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextField_Boleta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton_ActivarID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton_Aceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gfloppy-icono-6910-48.png"))); // NOI18N
        jButton_Aceptar.setText("Guardar");
        jButton_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_AceptarMouseClicked(evt);
            }
        });
        jButton_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AceptarActionPerformed(evt);
            }
        });

        jButton_Cancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jButton_Cancelar.setText("Regresar");
        jButton_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tema de tesis:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 0, 51))); // NOI18N

        jTextArea_TemaTesis.setColumns(20);
        jTextArea_TemaTesis.setRows(5);
        jScrollPane1.setViewportView(jTextArea_TemaTesis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trabajo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Lugar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lugar:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jTextArea_LugarDeTrabajo.setColumns(20);
        jTextArea_LugarDeTrabajo.setRows(5);
        jScrollPane2.setViewportView(jTextArea_LugarDeTrabajo);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Horario:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("HH: MM");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("A");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("HH: MM");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel_LugarLayout = new javax.swing.GroupLayout(jPanel_Lugar);
        jPanel_Lugar.setLayout(jPanel_LugarLayout);
        jPanel_LugarLayout.setHorizontalGroup(
            jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LugarLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel_LugarLayout.createSequentialGroup()
                        .addGroup(jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                                .addComponent(jTextField_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                                .addComponent(jTextField_Hora2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_LugarLayout.setVerticalGroup(
            jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_LugarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_LugarLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel11)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_LugarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Hora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_Lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, 340));

        jPanel_Trabajo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿Trabajas?:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        buttonGroup.add(jRadioButton_Si);
        jRadioButton_Si.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton_Si.setText("SIi");
        jRadioButton_Si.setNextFocusableComponent(jPanel_Trabajo);
        jRadioButton_Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_SiActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButton_No);
        jRadioButton_No.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jRadioButton_No.setSelected(true);
        jRadioButton_No.setText("NO");
        jRadioButton_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_NoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TrabajoLayout = new javax.swing.GroupLayout(jPanel_Trabajo);
        jPanel_Trabajo.setLayout(jPanel_TrabajoLayout);
        jPanel_TrabajoLayout.setHorizontalGroup(
            jPanel_TrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TrabajoLayout.createSequentialGroup()
                .addComponent(jRadioButton_Si)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_No)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_TrabajoLayout.setVerticalGroup(
            jPanel_TrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TrabajoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_TrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_Si)
                    .addComponent(jRadioButton_No))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel_Trabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 28, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/trabajo.jpg"))); // NOI18N
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Paterno :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 76, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Materno :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 116, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Boleta :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nombre :");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 43, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Director de Tesis :");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Correo electrónico :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Foto :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Teléfono celular :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Carrera :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Generación :");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        jPanel5.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 38, 130, -1));
        jPanel5.add(jTextField_AppPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 78, 130, -1));
        jPanel5.add(jTextField_AppMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 122, 130, -1));
        jPanel5.add(jTextField_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 130, -1));
        jPanel5.add(jTextField_Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 198, 130, -1));
        jPanel5.add(jTextField_Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 130, -1));
        jPanel5.add(jTextField_Generacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 130, -1));
        jPanel5.add(jTextField_DirectorDeTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 130, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("ID Director de Tesis :");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 20));
        jPanel5.add(jTextField_Id_DirectorDeTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 30, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tesis3.jpg"))); // NOI18N
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 230, 230));

        jTextField_Foto.setColumns(20);
        jTextField_Foto.setRows(5);
        jScrollPane3.setViewportView(jTextField_Foto);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        jTextField_Boleta.setColumns(20);
        jTextField_Boleta.setRows(5);
        jScrollPane4.setViewportView(jTextField_Boleta);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("ID:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Candidato");

        jButton_ActivarID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_ActivarID.setText("ActivarID");
        jButton_ActivarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActivarIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_ActivarID)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton_Aceptar)
                        .addGap(43, 43, 43)
                        .addComponent(jButton_Cancelar)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(575, 575, 575))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13)
                    .addComponent(jButton_ActivarID))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(158, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Aceptar)
                            .addComponent(jButton_Cancelar))
                        .addGap(71, 71, 71))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
  
     
    private void jButton_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_AceptarMouseClicked
      
        try
        {
        int id=Integer.parseInt(jTextField_ID.getText());
        String nom=jTextField_Nombre.getText();
        String appPaterno=jTextField_AppPaterno.getText();
        String appMaterno=jTextField_AppMaterno.getText();
        String foto =jTextField_Foto.getText();
        String boleta=jTextField_Boleta.getText();
        int celular=Integer.parseInt(jTextField_Telefono.getText());   
        String carrera=jTextField_Carrera.getText();
        String generación=jTextField_Generacion.getText();
        String temaDeTesis=jTextArea_TemaTesis.getText();
        int idDirectorDeTesis=Integer.parseInt(jTextField_Id_DirectorDeTesis.getText());
        String directorDeTesis=jTextField_DirectorDeTesis.getText();
        lugarDeTrabajo=jTextArea_LugarDeTrabajo.getText();
        hora=jTextField_Hora.getText()+"a"+jTextField_Hora2.getText();
        String correo=jTextField_Correo.getText();
        //--------------------------------------------------
        can.setIdCandidato(id);
        can.setIdAsesor(idDirectorDeTesis);
        can.setNombre(nom);
        can.setAppPaterno(appPaterno);
        can.setAppMaterno(appMaterno);
        can.setAdmitido("NO");
        can.setFoto(foto);
        can.setBoleta(boleta);
        can.setTeléfonoCelular(celular);
        can.setCarrera(carrera);
        can.setGeneración(generación);      
        can.setCorreoElectrónico(correo);
        can.setDirectorDeTesis(directorDeTesis);
        can.setTemaDeTesis(temaDeTesis);      
        can.setHorarioDeTrabajo(hora);
        can.setLugarDeTrabajo(lugarDeTrabajo);
        can.setTrabaja(trabajo);
        //--------------------------------------------------    
        canDB.AgregarCandidato(can);
        this.setVisible(false);
        newJfCandi.setVisible(true);
        newJfCandi.Actualizar();
       }
       catch(Exception e)
       {
            JOptionPane.showMessageDialog(null, "-->ERROR: " + e.getMessage());
       }
      
    }//GEN-LAST:event_jButton_AceptarMouseClicked

    private void jButton_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AceptarActionPerformed
  
    }//GEN-LAST:event_jButton_AceptarActionPerformed

    private void jButton_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelarActionPerformed
        this.setVisible(false);
        newJfCandi.setVisible(true);
    }//GEN-LAST:event_jButton_CancelarActionPerformed

    private void jRadioButton_SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_SiActionPerformed

        jPanel_Lugar.setVisible(true);
        trabajo="SI";
    }//GEN-LAST:event_jRadioButton_SiActionPerformed

    private void jRadioButton_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_NoActionPerformed
        jPanel_Lugar.setVisible(false);
        trabajo="NO";
        lugarDeTrabajo=null;
        hora=null;
    }//GEN-LAST:event_jRadioButton_NoActionPerformed

    private void jButton_ActivarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActivarIDActionPerformed
        jTextField_ID.setVisible(true);
    }//GEN-LAST:event_jButton_ActivarIDActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgregarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgregarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgregarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_AgregarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_AgregarCandidato().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
  
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton_Aceptar;
    private javax.swing.JButton jButton_ActivarID;
    private javax.swing.JButton jButton_Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Lugar;
    private javax.swing.JPanel jPanel_Trabajo;
    private javax.swing.JRadioButton jRadioButton_No;
    private javax.swing.JRadioButton jRadioButton_Si;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea_LugarDeTrabajo;
    private javax.swing.JTextArea jTextArea_TemaTesis;
    private javax.swing.JTextField jTextField_AppMaterno;
    private javax.swing.JTextField jTextField_AppPaterno;
    private javax.swing.JTextArea jTextField_Boleta;
    private javax.swing.JTextField jTextField_Carrera;
    private javax.swing.JTextField jTextField_Correo;
    private javax.swing.JTextField jTextField_DirectorDeTesis;
    private javax.swing.JTextArea jTextField_Foto;
    private javax.swing.JTextField jTextField_Generacion;
    private javax.swing.JTextField jTextField_Hora;
    private javax.swing.JTextField jTextField_Hora2;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Id_DirectorDeTesis;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Telefono;
    // End of variables declaration//GEN-END:variables
}
